### ISSUE TITLE
Fatal application error ocurred: Unsupported Thingsboard version : 3.8.1.7PAAS

### ISSUE THREAD

**Issue by Vaibhav0216** [thingsboard/flutter_thingsboard_app#162]
I am facing a issue on running flutter application of thingsboard like below:
```
⛔ Failed to init tbContext: ThingsboardError: message: [Unsupported ThingsBoard platform version: 3.8.1.7PAAS], errorCode: 2, status: null
⛔ #0      toThingsboardError (package:thingsboard_client/src/error/_thingsboard_error_handler_io.dart:89:18)
⛔ #1      ThingsboardClient.init (package:thingsboard_client/src/thingsboard_client_base.dart:247:13)
⛔ <asynchronous suspension>
⛔ #2      TbContext.init (package:thingsboard_app/core/context/tb_context.dart:126:7)
⛔ <asynchronous suspension>
⛔ #3      HasTbContext.initTbContext (package:thingsboard_app/core/context/has_tb_context.dart:41:5)
⛔ <asynchronous suspension>
```

ThingsBoard PE version : 3.8.1.7
Flutter ThingsBoard PE Mobile Application: 1.4.0
Dart ThingsBoard PE Client: ^2.0.0

please guide me on this issue.

**Comment by ybeshkarov** [comment]
You have to use PE app with PE platform.
And CE app with CE platform. 

As I answered you before please read the doc to know the difference https://thingsboard.io/docs/mobile/
