### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by jbanlles-vunkers** [thingsboard/flutter_thingsboard_app#177]
JavaScript console] ERROR: ERROR Error: Uncaught (in promise): ChunkLoadError: Loading chunk 8438 failed.
I/flutter (25501):   DEBUG │ 🐛 (timeout: https://portal.iot.vunkers.com/8438.6eea49670b3851e8.js)
I/flutter (25501):   DEBUG │ 🐛 ChunkLoadError
I/flutter (25501):   DEBUG │ 🐛     at t.f.j (https://portal.iot.vunkers.com/runtime.02770f7daec302a5.js:1:4387)
I/flutter (25501):   DEBUG │ 🐛     at https://portal.iot.vunkers.com/runtime.02770f7daec302a5.js:1:1267
I/flutter (25501):   DEBUG │ 🐛     at Array.reduce (<anonymous>)
I/flutter (25501):   DEBUG │ 🐛     at t.e (https://portal.iot.vunkers.com/runtime.02770f7daec302a5.js:1:1246)
I/flutter (25501):   DEBUG │ 🐛     at loadChildren (https://portal.iot.vunkers.com/main.5c16aadaf2f1b347.js:1:2017615)
I/flutter (25501):   DEBUG │ 🐛     at ui.loadModuleFactoryOrRoutes (https://portal.iot.vunkers.com/vendor.82d3bc22f4287f7e.js:1:2539180)
I/flutter (25501):   DEBUG │ 🐛     at ui.loadChildren (https://portal.iot.vunkers.com/vendor.82d3bc22f4287f7e.js:1:2538706)
I/flutter (25501):   DEBUG │ 🐛     at https://portal.iot.vunkers.com/vendor.82d3bc22f4287f7e.js:1:2530578
I/flutter (25501):   DEBUG │ 🐛     at Ce (https://portal.iot.vunkers.com/vendor.82d3bc22f4287f7e.js:1:548292)
I/flutter (25501):   DEBUG │ 🐛     at Le (https://portal.iot.vunkers.com/vendor.82d3bc22f4287f7e.js:1:548227)
Access denied finding property "vendor.debug.bq.dump"
(26341): Access denied finding property "vendor.debug.sf.stc_interval"

E/libc    (24402): Access denied finding property "vendor.debug.bq.line"
>newInstance(IIIIJ)Landroid/media/ImageReader; (dark greylist, linking)

This happens to me when I want to enter a panel. What solution is there?

**Comment by ybeshkarov** [comment]
@vvlladd28 could you please take a look?
