### ISSUE TITLE
The versions after 2453bd9 are not working with ThingsBoard 3.6.3

### ISSUE THREAD

**Issue by maksonlee** [thingsboard/flutter_thingsboard_app#79]
```
ThingsboardError (ThingsboardError: message: [Path '/api/notifications/unread/count': Not Found], errorCode: 32, status: 404
#0      toThingsboardError (package:thingsboard_client/src/error/_thingsboard_error_handler_io.dart:89:18)
#1      HttpInterceptor.onError (package:thingsboard_client/src/interceptor/http_interceptor.dart:104:19)
#2      QueuedInterceptor._handleQueue (package:dio/src/interceptor.dart:423:17)
#3      QueuedInterceptor._handleError (package:dio/src/interceptor.dart:399:5)
#4      DioMixin.fetch.errorInterceptorWrapper.<anonymous closure>.handleError (package:dio/src/dio_mixin.dart:429:13)
#5      new Future.<anonymous closure> (dart:async/future.dart:256:37)
```
thingsboard_client 1.1.1 is not working with ThingsBoard 3.6.3, we don't have '/api/notifications/unread/count' there.
![image](https://github.com/thingsboard/flutter_thingsboard_app/assets/7221781/6765e80f-4299-4108-b0b5-53924075c28c)

**Comment by ybeshkarov** [comment]
Hello @maksonlee!

The system is functional, but you might encounter the error messages you described. This is due to a pending backend update, after which these errors should disappear.

We apologize for the inconvenience.

**Comment by maksonlee** [comment]
Never mind, just want to know the version compatibility between this App and ThingsBoard.
